services:
  netsky:
    build: .
    container_name: microsoft-rewards-script
    restart: unless-stopped

    # Volume mounts: Specify a location where you want to save the files on your local machine.
    volumes:
      - ./src/accounts.jsonc:/usr/src/microsoft-rewards-script/dist/accounts.jsonc:ro
      - ./src/config.jsonc:/usr/src/microsoft-rewards-script/dist/config.jsonc:ro
      - ./sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions # Optional, saves your login session
      - ./logs:/usr/src/microsoft-rewards-script/logs # Mount logs directory
  
    environment:
      TZ: "America/Bogota" # Set your timezone for proper scheduling
      NODE_ENV: "production"
      CRON_SCHEDULE: "0 7,17 * * *" # Twice per day: 07:00 and 17:00 (local TZ)
      RUN_ON_START: "true" # Runs the script on container startup
      EXPECTED_DAILY_RUNS: "2" # Enforce exactly two successful runs per day
  
      # Start-time randomization (uncomment to customize or disable)
      #MIN_SLEEP_MINUTES: "5"
      #MAX_SLEEP_MINUTES: "50"
      SKIP_RANDOM_SLEEP: "false"

    # Optional resource limits for the container
    mem_limit: 4g
    cpus: 2

    # Health check - monitors if cron daemon is running to ensure scheduled jobs can execute
    # Container marked unhealthy if cron process dies
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep cron > /dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Security hardening
    security_opt:
      - no-new-privileges:true