name: Microsoft Rewards Bot

on:
  workflow_dispatch:
  schedule:
    # Runs daily, starting at a random time between 10:00 and 12:00 UTC.
    - cron: '0 10 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create accounts.jsonc
        run: echo '${{ secrets.ACCOUNTS_JSON }}' > src/accounts.jsonc

      - name: Add random delay
        run: |
          DELAY_SECONDS=$((RANDOM % 7200))
          echo "Sleeping for $DELAY_SECONDS seconds to randomize start time..."
          sleep $DELAY_SECONDS

      - name: Run bot
        run: npm start